name: "Spellchecker CLI Summary"
description: "Output checks, issues, and job summary from Spellchecker CLI"
author: Austen Stone
branding:
  icon: "check-circle"
  color: "yellow"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  file-json:
    default: spell-check.json
    description: The JSON file output by spellchecker-cli-action
    required: false
  files-changed:
    default: '**/*.md'
    description: Files changed
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
